# Backend Configuration for GitHub + Decap Bridge (The Correct Method)
backend:
  name: github
  repo: finestxxx/cleaning-service
  branch: main
  
  # These two lines tell the 'github' backend to use Decap Bridge for authentication
  base_url: https://decap-bridge.onrender.com
  auth_endpoint: auth

# Media files (images) configuration
media_folder: "assets/images"
public_folder: "/cleaning-service/assets/images"

# Add a link back to your live site from the admin panel
site_url: https://finestxxx.github.io/cleaning-service/

# Collections (your content) - This part remains the same.
collections:
  - name: "pages"
    label: "Page Content"
    files:
      - file: "_data/homepage.json"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Site Logo Text", name: "logo_text", widget: "string", default: "Sparkle Clean" }
          - { label: "Hero Section Title", name: "hero_title", widget: "string" }
          - { label: "Hero Section Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Hero Section Background Image", name: "hero_image", widget: "image" }
          - { label: "About Us Section Title", name: "about_title", widget: "string" }
          - { label: "About Us Description", name: "about_description", widget: "markdown" }
          - { label: "About Us Image", name: "about_image", widget: "image" }
          - { label: "Services Section Title", name: "services_title", widget: "string" }
          - label: "Services List"
            name: "services"
            widget: "list"
            fields:
              - { label: "Icon (Font Awesome Class)", name: "icon", widget: "string", hint: "e.g., fas fa-home" }
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
          - { label: "Pricing Section Title", name: "pricing_title", widget: "string" }
          - label: "Pricing Plans"
            name: "pricing_plans"
            widget: "list"
            fields:
              - { label: "Plan Title", name: "title", widget: "string" }
              - { label: "Price", name: "price", widget: "string", hint: "e.g., $150" }
              - { label: "Is this the popular plan?", name: "is_popular", widget: "boolean", default: false }
              - { label: "Features", name: "features", widget: "list" }
          - { label: "Testimonials Section Title", name: "testimonials_title", widget: "string" }
          - label: "Testimonials"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: "Client Image", name: "image", widget: "image" }
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Author", name: "author", widget: "string" }
          - { label: "Contact Section Title", name: "contact_title", widget: "string" }
          - { label: "Footer Text", name: "footer_text", widget: "string" }